### PR TITLE
Issue/3

### LINKED ISSUE #1: Timeout mechanism for file listing
trinodb/trino#1723

### LINKED ISSUE #3: [feat] timeout mechanism for listing files
Requirement: The list function in class CachingDirectoryLister should have a timeout mechanism for listing files. Subtask for #1

### LINKED ISSUE #4: [feat] throw timeout exception if file listening take to much time
Requirement: The list function in class CachingDirectoryLister should throw a timeout exception if listing files takes more time than the set limit. Subtask for #1

### LINKED ISSUE #6: [feat] setter for the tiemout field
The class CachingDirectoryLister should have a setter for its timeout limit field. #1

### LINKED ISSUE #7: [feat] Include a timeout limit field in the CachingDirectoryLister
Requirement: The class CachingDirectoryLister should have a timeout limit field with a default value. Subtask for https://github.com/DD2480-Group26/trino/issues/1

### PR DESCRIPTION
**Pull request by ElisabethChen**
feat #3 created a timeout mechanism in the method list in class CachingDirectoryLister. It includes issues #7 and #4.

### CODE REVIEW

**Comment by cadye** [comment]
I can't really understand if issue #6 is part of this or not. there are 2 commits mentioning it, but the setter does not seem to be in the pull request? The pull request comment does also not mention issue #6.

I would like a clarification of what functions are included in this pull request. Is it "list", "listExecuter", and "getFileListingTimeout"?

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java [hunk 1]
```diff
@@ -181,6 +238,10 @@ public LocatedFileStatus next()
         };
     }
 
+    public Duration getFileListingTimeout() {
+        return fileListingTimeout;
```
Comment (juliaBystrom) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java:244]: When rebasing my branch with the configuration against your branch I will update this value to be the configurable fileListingTimeout :) Great!

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java [hunk 2]
```diff
@@ -87,20 +95,69 @@ private static SchemaTablePrefix parseTableName(String tableName)
...
+     * the field variable fileListingTimeout) the Thread running listExecuter will 
+     * be interrupted and a RuntimeException will be thrown. 
+     * 
+     * @param fs FileSystem, see: {@link org.apache.hadoop.fs.FileSystem}
+     * @param table Table, see: {@link io.trino.plugin.hive.metastore.Table}
+     * @param path  Path, see: {@link org.apache.hadoop.fs.Path}
+     * @return an iterator that runs over FileStatus-Object that inclues a file's block 
+     * locations
+     * @throws IOException
+     * @throws RuntimeException
```
Comment (juliaBystrom) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java:113]: I am a bit undecided about javadoc for this project. It is good but I did not find the rest of the code to be using it. But do you think it is beneficial enough to keep it?

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java [hunk 3]
```diff
@@ -87,20 +95,69 @@ private static SchemaTablePrefix parseTableName(String tableName)
...
+            throw new RuntimeException(e);
+        } catch (ExecutionException e) {
+            // error happened while executing listExecuter() - shut down this method
+            System.out.println(e);
+            timeoutExecutorService.shutdownNow();
+            throw new RuntimeException(e);
+        } catch (TimeoutException e) {
+            // timeout expired, stop this method from running and print an error message
+            future.cancel(true);
+            System.out.println(e);
```
Comment (juliaBystrom) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java]: The praxis for printing errors is using `System.err.println()` instead of a regular println.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java [hunk 4]
```diff
@@ -87,20 +95,69 @@ private static SchemaTablePrefix parseTableName(String tableName)
...
+                .submit(() -> listExecuter(fs, table, path));
+        try {
+            return future.get(fileListingTimeout.toMillis(), TimeUnit.MILLISECONDS);
+        } catch (InterruptedException e) {
+            // something interrupted, probably your service is shutting down
+            timeoutExecutorService.shutdownNow();
+            throw new RuntimeException(e);
+        } catch (ExecutionException e) {
+            // error happened while executing listExecuter() - shut down this method
+            System.out.println(e);
```
Comment (juliaBystrom) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java]: The praxis for printing errors is using `System.err.println()` instead of a regular println.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java [hunk 5]
```diff
@@ -87,20 +95,69 @@ private static SchemaTablePrefix parseTableName(String tableName)
...
-            throws IOException
-    {
+            throws IOException, RuntimeException {
+        ExecutorService timeoutExecutorService = Executors.newSingleThreadExecutor();
+        Future<RemoteIterator<LocatedFileStatus>> future = timeoutExecutorService
+                .submit(() -> listExecuter(fs, table, path));
+        try {
+            return future.get(fileListingTimeout.toMillis(), TimeUnit.MILLISECONDS);
+        } catch (InterruptedException e) {
+            // something interrupted, probably your service is shutting down
```
Comment (juliaBystrom) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java]: This comment is a bit unclear. Stating "probably your service is shutting down" is unecesarry.

**Review by juliaBystrom — COMMENTED** [review]
Gave some comments for review. Overall the code looks good :)

**Comment by ElisabethChen** [comment]
> I can't really understand if issue #6 is part of this or not. there are 2 commits mentioning it, but the setter does not seem to be in the pull request? The pull request comment does also not mention issue #6.

the commits should be changed when merging /squashing. It seems like Julia did Issue #6  on her part so after a previous discussion with her, we said that I should delete setters in my part. I think I mentioned this in the latest commit but I should maybe also mention that I removed issue #6 and it's done in Julia's part.
 
> I would like a clarification of what functions are included in this pull request. Is it "list", "listExecuter", and "getFileListingTimeout"?

yes, it is those methods.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java (hunk 2 above)
Comment (ElisabethChen) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java:113]: I personally think it's better to have than not to have. At least I would be happy if the function have descriptions =).

**Review by juliaBystrom — APPROVED** [review]

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java (hunk 2 above)
Comment (cadye) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java:113]: I also think that comments in general are better, but the fact is that the project does not have comments in the code, so I think it would be better to follow that style, even if you disagree with it.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java [hunk 6]
```diff
@@ -87,20 +97,69 @@ private static SchemaTablePrefix parseTableName(String tableName)
...
+     * remotely. The elements are FileStatus-objects that includes a file's block 
+     * locations. 
+     * @param fs FileSystem, see: {@link org.apache.hadoop.fs.FileSystem}
+     * @param table Table, see: {@link io.trino.plugin.hive.metastore.Table}
+     * @param path  Path, see: {@link org.apache.hadoop.fs.Path}
+     * @return an iterator that runs over FileStatus-Object that inclues a file's block 
+     * locations
+     * @throws IOException
+     */
+    public RemoteIterator<LocatedFileStatus> listExecuter(FileSystem fs, Table table, Path path)
```
Comment (cadye) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java:153]: should listExecuter be private? don't understand how it works, but I would guess that it is only a helper function for "list" function. (I also don't understand why the listExecuter function doesn't show up in this pull request.)

**Review by cadye — APPROVED** [review]

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java (hunk 2 above)
Comment (hemenali11) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java:113]: I agree with the others about the comments, very good to have but the project does not have in its style.

**Review by hemenali11 — APPROVED** [review]
good job
